site_name: CloudConvertR 

theme:
  name: material
  logo: assets/CloudConvertR-light.png
  favicon: assets/CloudConvertR-light.png
  features:
    - content.code.copy
    - content.code.annotate
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: 'blue grey'
      toggle:
        icon: material/brightness-7
        name: Switch to system preference

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: 'blue grey'
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

extra_css:
  - assets/css/custom.css

repo_url: https://github.com/Adneycm/CloudConvertR
repo_name: Adneycm/CloudConvertR


nav:
  - index.md
  - infraestrutura.md
  - instalacao.md
  - implementacao.md
  - utilizacao.md


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
    - mkdocs-video